runtime: nodejs10

# Health checks are enabled by default.
# https://cloud.google.com/appengine/docs/flexible/python/reference/app-yaml#updated_health_checks
# TODO: consider adding 'readiness checks'.
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Scaling is automatic.
# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref#scaling_elements
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 1
#   min_idle_instances: 0
#   # max_concurrent_requests: 5 # (10: 5 .. 80)
#   target_cpu_utilization: 0.95 # (0.6: 0.5 .. 0.95)
#   target_throughput_utilization: 0.95 # (0.6: 0.5 .. 0.95)

# Web request handlers.
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
